require_relative './gmt'
require_relative './noaa_soap'
require_relative './get_water_level'
require_relative './get_wind'
require_relative './cli'
#require_relative './cpdundon/cli/app/take2/version'
#require_relative './cpdundon/cli/app/take2'

require 'cpdundon_cli_app_take3'
require 'time'
require 'savon'
