require_relative './noaa_soap'
require_relative './cli'
require_relative './cli_current'
require_relative './gmt'
require_relative './get_water_level'
require_relative './get_wind'
require_relative './get_active_stations'
require_relative './station'
require_relative './calc_current'

require 'nokogiri'
require 'savon'
require 'time'
